_base_ = '../../fqdet/base/v1.py'

model = dict(
    requires_masks=True,
    head_cfgs=[
        *_base_.model.head_cfgs,
        dict(
            type='ModRoIHead',
            cls_agn_masks=False,
            roi_ext_cfg=dict(
                type='MMDetRoIExtractor',
                mmdet_roi_ext_cfg=dict(
                    type='mmdet.GenericRoIExtractor',
                    aggregation='concat',
                    roi_layer=dict(type='SimpleRoIAlign', output_size=14),
                    out_channels=256,
                    featmap_strides=[4],
                ),
            ),
            mask_logits_cfg=[
                dict(
                    type='QryMapFusion',
                    in_key='roi_feats',
                    qry_key='roi_qry_feats',
                    out_key='roi_feats',
                    pre_cat_cfg=[
                        dict(
                            type='nn.Linear',
                            in_features=256,
                            out_features=256,
                            bias=True,
                        ),
                        dict(
                            type='nn.ReLU',
                            inplace=True,
                        ),
                    ],
                    post_cat_cfg=[
                        dict(
                            type='nn.Conv2d',
                            in_channels=512,
                            out_channels=256,
                            kernel_size=1,
                            bias=True,
                        ),
                        dict(
                            type='nn.ReLU',
                            inplace=True,
                        ),
                        dict(
                            type='nn.Conv2d',
                            in_channels=256,
                            out_channels=256,
                            kernel_size=1,
                            bias=True,
                        ),
                    ],
                ),
                dict(
                    type='StorageApply',
                    in_key='roi_feats',
                    out_key='mask_logits',
                    module_cfg=[
                        dict(
                            type='mmdet.ConvModule',
                            num_layers=4,
                            in_channels=256,
                            out_channels=256,
                            kernel_size=3,
                            padding=1,
                        ),
                        dict(
                            type='nn.ConvTranspose2d',
                            in_channels=256,
                            out_channels=256,
                            kernel_size=2,
                            stride=2,
                        ),
                        dict(
                            type='nn.ReLU',
                            inplace=True,
                        ),
                        dict(
                            type='nn.Conv2d',
                            in_channels=256,
                            out_channels=80,
                            kernel_size=1,
                        ),
                    ],
                ),
                dict(
                    type='StorageCopy',
                    in_key='mask_logits',
                    out_key='coarse_mask_logits',
                    copy_type='assign',
                ),
                dict(
                    type='StorageApply',
                    in_key='feat_maps',
                    out_key='feat_map_0',
                    module_cfg=dict(
                        type='GetItem',
                        index=0,
                    ),
                ),
                dict(
                    type='StorageAdd',
                    module_key='point_head',
                    module_cfg=[
                        dict(
                            type='BoxToImgPts',
                            in_key='roi_sample_xy',
                            boxes_key='roi_boxes',
                            out_key='img_sample_xy',
                        ),
                        dict(
                            type='MapSampler2d',
                            in_map_key='feat_map_0',
                            in_pts_key='img_sample_xy',
                            batch_ids_key='roi_batch_ids',
                            out_key='fine_feats',
                            grid_sample_kwargs=dict(
                                mode='bilinear',
                                align_corners=False,
                            ),
                        ),
                        dict(
                            type='BaseSampler2d',
                            in_map_key='coarse_mask_logits',
                            in_pts_key='roi_sample_xy',
                            out_key='coarse_feats',
                            grid_sample_kwargs=dict(
                                mode='bilinear',
                                align_corners=False,
                            ),
                        ),
                        *[[
                            dict(
                                type='Cat',
                                in_keys=['fine_feats', 'coarse_feats'],
                                out_key='fine_feats',
                                dim=2,
                            ),
                            dict(
                                type='StorageApply',
                                in_key='fine_feats',
                                out_key='fine_feats',
                                module_cfg=dict(
                                    type='nn.Linear',
                                    in_features=336,
                                    out_features=256,
                                ),
                            ),
                        ] for _ in range(3)],
                        dict(
                            type='StorageApply',
                            in_key='fine_feats',
                            out_key='point_logits',
                            module_cfg=dict(
                                type='nn.Linear',
                                in_features=256,
                                out_features=80,
                            ),
                        ),
                    ],
                ),
                dict(
                    type='StorageCondition',
                    cond_key='is_inference',
                    module_cfg=dict(
                        type='StorageIterate',
                        num_iters=3,
                        last_iter_key='last_iter',
                        module_cfg=[
                            dict(
                                type='StorageApply',
                                in_key='mask_logits',
                                out_key='mask_logits',
                                module_cfg=dict(
                                    type='Interpolate',
                                    scale_factor=2.0,
                                    mode='bilinear',
                                    align_corners=False,
                                ),
                            ),
                            dict(
                                type='SparseBool2d',
                                in_key='mask_logits',
                                out_key='point_bool',
                                num_updates=784,
                                force_key='last_iter',
                                scale_factor=2.0,
                            ),
                            dict(
                                type='StorageCondition',
                                cond_key='point_bool',
                                module_cfg=[
                                    dict(
                                        type='SelectClass',
                                        in_key='mask_logits',
                                        labels_key='roi_labels',
                                        out_key='cls_mask_logits',
                                    ),
                                    dict(
                                        type='Uncertainty',
                                        in_key='cls_mask_logits',
                                        out_key='uncertainty_map',
                                    ),
                                    dict(
                                        type='GridPts2d',
                                        in_key='uncertainty_map',
                                        num_pts=784,
                                        out_ids_key='roi_sample_ids',
                                        out_key='roi_sample_xy',
                                    ),
                                    dict(
                                        type='StorageGetApply',
                                        module_key='point_head',
                                    ),
                                    dict(
                                        type='SparseInsert2d',
                                        in_key='mask_logits',
                                        ins_ids_key='roi_sample_ids',
                                        ins_feats_key='point_logits',
                                    ),
                                ],
                            ),
                        ],
                    ),
                ),
                dict(
                    type='SelectClass',
                    in_key='mask_logits',
                    labels_key='roi_labels',
                    out_key='mask_logits',
                ),
                dict(
                    type='StorageCondition',
                    cond_key='is_training',
                    module_cfg=[
                        dict(
                            type='DenseRoIMaskTargets',
                        ),
                        dict(
                            type='StorageApply',
                            in_key='mask_logits',
                            out_key='mask_loss',
                            storage_kwargs={'mask_targets': 'label'},
                            filter_kwargs=[],
                            module_cfg=dict(
                                type='MaskLoss',
                                mask_loss_cfg=dict(
                                    type='mmdet.CrossEntropyLoss',
                                    use_sigmoid=True,
                                    reduction='sum',
                                    loss_weight=1.0,
                                ),
                            ),
                        ),
                        dict(
                            type='BinaryAccuracy',
                            pred_key='mask_logits',
                            tgt_key='mask_targets',
                            out_key='mask_acc',
                        ),
                        dict(
                            type='PointRendTrainPts2d',
                            in_key='mask_logits',
                            labels_key='roi_labels',
                            out_key='roi_sample_xy',
                            num_pts=196,
                            oversample_ratio=3.0,
                            importance_ratio=0.75,
                        ),
                        dict(
                            type='StorageGetApply',
                            module_key='point_head',
                        ),
                        dict(
                            type='StorageApply',
                            in_key='point_logits',
                            out_key='point_logits',
                            module_cfg=[
                                dict(
                                    type='Transpose',
                                    dim0=1,
                                    dim1=2,
                                ),
                                dict(
                                    type='Unsqueeze',
                                    dim=3,
                                ),
                            ],
                        ),
                        dict(
                            type='SelectClass',
                            in_key='point_logits',
                            labels_key='roi_labels',
                            out_key='point_logits',
                        ),
                        dict(
                            type='StorageTransfer',
                            in_keys=['masks'],
                            dict_key='tgt_dict',
                            out_keys=['tgt_map'],
                            transfer_mode='in',
                        ),
                        dict(
                            type='StorageApply',
                            in_key='tgt_map',
                            out_key='tgt_map',
                            module_cfg=[
                                dict(
                                    type='Float',
                                ),
                                dict(
                                    type='Unsqueeze',
                                    dim=1,
                                ),
                            ],
                        ),
                        dict(
                            type='MapSampler2d',
                            in_map_key='tgt_map',
                            in_pts_key='img_sample_xy',
                            batch_ids_key='matched_tgt_ids',
                            out_key='point_targets',
                            grid_sample_kwargs=dict(
                                mode='bilinear',
                                align_corners=False,
                            ),
                        ),
                        dict(
                            type='StorageApply',
                            in_key='point_logits',
                            out_key='point_loss',
                            storage_kwargs={'point_targets': 'label'},
                            filter_kwargs=[],
                            module_cfg=dict(
                                type='MaskLoss',
                                mask_loss_cfg=dict(
                                    type='mmdet.CrossEntropyLoss',
                                    use_sigmoid=True,
                                    reduction='sum',
                                    loss_weight=1.0,
                                ),
                            ),
                        ),
                        dict(
                            type='BinaryAccuracy',
                            pred_key='point_logits',
                            tgt_key='point_targets',
                            out_key='point_acc',
                        ),
                        dict(
                            type='StorageTransfer',
                            in_keys=['mask_loss', 'point_loss'],
                            dict_key='loss_dict',
                            transfer_mode='out',
                        ),
                        dict(
                            type='StorageTransfer',
                            in_keys=['mask_acc', 'point_acc'],
                            dict_key='analysis_dict',
                            transfer_mode='out',
                        ),
                    ],
                ),
            ],
            roi_paster_cfg=dict(
                type='MMDetRoIPaster',
            ),
            dup_attrs=dict(
                type='nms',
                nms_candidates=1000,
                nms_thr=0.5,
            ),
            max_segs=100,
        ),
    ],
)
