model = dict(
    type='GCT',
    requires_masks=False,
    map_cfg=dict(
        type='ResNet',
        name='resnet50',
        out_ids=[2],
    ),
    graph_cfgs=[
        dict(
            type='GraphToGraph',
            in_graph_id=0,
            out_graph_id=1,
            node_score_cfg=[
                dict(
                    type='nn.Linear',
                    in_features=256,
                    out_features=96,
                    bias=True,
                    ),
                dict(
                    type='TwoStepMLP',
                    num_layers=1,
                    in_size=96,
                    hidden_size=384,
                    out_size=96,
                    norm1='layer',
                    norm2='',
                    act_fn1='',
                    act_fn2='relu',
                    skip=True,
                ),
            ],
            edge_score_cfg=[
                dict(
                    type='nn.Linear',
                    in_features=256,
                    out_features=96,
                    bias=True,
                ),
                dict(
                    type='TwoStepMLP',
                    num_layers=1,
                    in_size=96,
                    hidden_size=384,
                    out_size=96,
                    norm1='layer',
                    norm2='',
                    act_fn1='',
                    act_fn2='relu',
                    skip=True,
                ),
                dict(
                    type='EdgeDotProduct',
                    implementation='pytorch-custom',
                ),
            ],
        ),
    ],
)
