---
layers:

  # Top-down layer
  - name: 'top-down'
    in:
      - - 0
        - 1
    out: 
      - - 3

    # Top-down operations
    operations:

      # Upsample
      - type: 'interpolate'
        shape: True
        mode: 'bilinear'
        align_corners: False
        in: 
          - - 0
            - 1
        out: 
          - - 2

      # Residual addition
      - type: 'add'
        in:
          - - 1
            - 2
        out:
          - - 3

  # Bottom-up layer
  - name: 'bottom-up'
    in:
      - - 0
        - 1
    out:
      - - 3

    # Bottom-up operations
    operations:

      # Downsampling convolution
      - type: 'conv2d'
        out_channels: 256
        kernel_size: 3
        stride: 2
        padding: 1
        in:
          - - 0
        out:
          - - 2

      # Residual addition
      - type: 'add'
        in:
          - - 1
            - 2
        out:
          - - 3

  # PA layer
  - name: 'pa'
    in:
      - - 0 # P7
        - 1 # P6
        - 2 # P5
        - 3 # P4
        - 4 # P3
    out:
      - - 18 # P3
        - 19 # P4
        - 20 # P5
        - 21 # P6
        - 22 # P7

    # PA operations
    operations:

      # Top-down layer
      - type: 'layer'
        name: 'top-down'
        in:
          - - 0 # P7
            - 1 # P6
          - - 5 # P6
            - 2 # P5
          - - 6 # P5
            - 3 # P4
          - - 7 # P4
            - 4 # P3
        out:
          - - 5 # P6
          - - 6 # P5
          - - 7 # P4
          - - 8 # P3

      # Conv layer 1
      - type: 'conv2d'
        out_channels: 256
        kernel_size: 3
        padding: 1
        in:
          - - 0 # P7
          - - 5 # P6
          - - 6 # P5
          - - 7 # P4
          - - 8 # P3
        out:
          - - 9  # P7
          - - 10 # P6
          - - 11 # P5
          - - 12 # P4
          - - 13 # P3

      # Bottom-up layer
      - type: 'layer'
        name: 'bottom-up'
        in:
          - - 13 # P3
            - 12 # P4
          - - 14 # P4
            - 11 # P5
          - - 15 # P5
            - 10 # P6
          - - 16 # P6
            - 9  # P7
        out:
          - - 14 # P4
          - - 15 # P5
          - - 16 # P6
          - - 17 # P7

      # Conv layer 2
      - type: 'conv2d'
        out_channels: 256
        kernel_size: 3
        padding: 1
        in:
          - - 13 # P3
          - - 14 # P4
          - - 15 # P5
          - - 16 # P6
          - - 17 # P7
        out:
          - - 18 # P3
          - - 19 # P4
          - - 20 # P5
          - - 21 # P6
          - - 22 # P7

operations:

  # Lateral projection
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in:
      - - 2
      - - 1
      - - 0
    out:
      - - 3
      - - 4
      - - 5

  # Get P6 from original P5
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    stride: 2
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in: 
      - - 2
    out: 
      - - 6

  # Get ReLU P6
  - type: 'relu'
    inplace: True
    in: 
      - - 6
    out: 
      - - 7

  # Get P7 from ReLU P6
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    stride: 2
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in: 
      - - 7
    out: 
      - - 8

  # PA
  - type: 'layer'
    name: 'pa'
    num_layers: 1
    in:
      - - 8 # P7
        - 6 # P6
        - 3 # P5
        - 4 # P4
        - 5 # P3
    out:
      - - 9  # P3 new
        - 10 # P4 new
        - 11 # P5 new
        - 12 # P6 new
        - 13 # P7 new
    out_to_in:
      - - 5 # P3 old
        - 4 # P4 old
        - 3 # P5 old
        - 6 # P6 old
        - 8 # P7 old

outputs:
  - 9  # P3
  - 10 # P4
  - 11 # P5
  - 12 # P6
  - 13 # P7
...
