---
feat_sizes:
  - 512  # P3 map
  - 1024 # P4 map
  - 2048 # P5 map

layers:

  # Top-down layer
  - name: 'top-down'
    in:
      - - 0
        - 1
    out: 
      - - 5

    # Top-down operations
    operations:

      # Feature normalization
      - type: 'featurenorm'
        num_groups: 8
        in:
          - - 0
        out:
          - - 2

      # Top-down delta projection
      - type: 'attn2d'
        out_channels: 256
        kernel_size: 1
        num_heads: 8
        attn_mode: 'cross'
        pos_attn: False
        q_stride: 2
        qk_norm: 'sigmoid'
        in:
          - - 1
            - 2
        out:
          - - 3

      # Upsample
      - type: 'interpolate'
        shape: True
        mode: 'nearest'
        in: 
          - - 3
            - 1
        out: 
          - - 4

      # Fuse
      - type: 'add'
        in:
          - - 1
            - 4
        out:
          - - 5

  # Bottom-up layer
  - name: 'bottom-up'
    in:
      - - 0
        - 1
    out: 
      - - 4

    # Bottom-up operations
    operations:

      # Feature normalization
      - type: 'featurenorm'
        num_groups: 8
        in:
          - - 0
        out:
          - - 2

      # Bottom-up delta projection
      - type: 'attn2d'
        out_channels: 256
        kernel_size: 3
        stride: 2
        padding: 1
        num_heads: 8
        attn_mode: 'cross'
        in:
          - - 1
            - 2
        out:
          - - 3

      # Fuse
      - type: 'add'
        in:
          - - 1
            - 3
        out:
          - - 4

  # PA layer
  - name: 'pa'
    in:
      - - 0 # P7
        - 1 # P6
        - 2 # P5
        - 3 # P4
        - 4 # P3
    out: 
      - - 8  # P3
        - 9  # P4
        - 10 # P5
        - 11 # P6
        - 12 # P7
    
    # PA operations
    operations:

      # Top-down layer
      - type: 'layer'
        name: 'top-down'
        in:
          - - 0 # P7
            - 1 # P6
          - - 5 # P6
            - 2 # P5
          - - 6 # P5
            - 3 # P4
          - - 7 # P4
            - 4 # P3
        out:
          - - 5 # P6
          - - 6 # P5
          - - 7 # P4
          - - 8 # P3

      # Bottom-up layer
      - type: 'layer'
        name: 'bottom-up'
        in:
          - - 8  # P3
            - 7  # P4
          - - 9  # P4
            - 6  # P5
          - - 10 # P5
            - 5  # P6
          - - 11 # P6
            - 0  # P7
        out:
          - - 9  # P4
          - - 10 # P5
          - - 11 # P6
          - - 12 # P7

operations:

  # Lateral projection
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in:
      - - 2
      - - 1
      - - 0
    out:
      - - 3
      - - 4
      - - 5

  # Get P6 from original P5
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    stride: 2
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in: 
      - - 2
    out: 
      - - 6

  # Get ReLU P6
  - type: 'relu'
    in: 
      - - 6
    out: 
      - - 7

  # Get P7 from ReLU P6
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    stride: 2
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in: 
      - - 7
    out: 
      - - 8

  # PA
  - type: 'layer'
    name: 'pa'
    num_layers: 2
    in:
      - - 8 # P7
        - 6 # P6
        - 3 # P5
        - 4 # P4
        - 5 # P3
    out:
      - - 9  # P3 new
        - 10 # P4 new
        - 11 # P5 new
        - 12 # P6 new
        - 13 # P7 new
    out_to_in:
      - - 5 # P3 old
        - 4 # P4 old
        - 3 # P5 old
        - 6 # P6 old
        - 8 # P7 old

  # Output projection
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in:
      - - 9  # P3
      - - 10 # P4
      - - 11 # P5
      - - 12 # P6
      - - 13 # P7
    out:
      - - 14 # P3
      - - 15 # P4
      - - 16 # P5
      - - 17 # P6
      - - 18 # P7

outputs:
    - 14 # P3
    - 15 # P4
    - 16 # P5
    - 17 # P6
    - 18 # P7
...
