---
feat_sizes:
  - 512  # P3 map
  - 1024 # P4 map
  - 2048 # P5 map

operations:

  # Lateral projection
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in:
      - 2
      - 1
      - 0
    out:
      - 3
      - 4
      - 5

  # Upsample P5 to P4
  - type: 'interpolate'
    shape: 4
    mode: 'nearest'
    in: 3
    out: 6

  # Fuse at P4 level
  - type: 'add'
    in:
      - - 4
        - 6
    out:
      - 7

  # Upsample P4 to P3
  - type: 'interpolate'
    shape: 5
    mode: 'nearest'
    in: 7
    out: 8

  # Fuse at P3 level
  - type: 'add'
    in:
      - - 5
        - 8
    out:
      - 9

  # Output projection
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in:
      - 3
      - 7
      - 9
    out:
      - 10
      - 11
      - 12

  # Get P6 from original P5
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    stride: 2
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in: 2
    out: 13

  # Get ReLU P6
  - type: 'relu'
    in: 13
    out: 14

  # Get P7 from ReLU P6
  - type: 'conv2d'
    out_channels: 256
    kernel_size: 3
    stride: 2
    padding: 1
    weight_init: 'kaiming_uniform_'
    weight_init_a: 1
    bias_init: 'zeros_'
    in: 14
    out: 15

outputs:
    - 12 # P3 map
    - 11 # P4 map
    - 10 # P5 map
    - 13 # P6 map
    - 15 # P7 map
...
